<script setup>
import AppIcon from './AppIcon.vue';import {useAuthStore} from '../stores/auth';import {useRouter} from 'vue-router'
const props=defineProps({mode:{type:String,default:'admin'}});const auth=useAuthStore(),router=useRouter()
const portal=[['/portal','home','工作台'],['/portal/rfqs','search','询报价'],['/portal/orders','order','采购订单'],['/portal/delivery','truck','交付预约'],['/portal/quality','quality','质量协同'],['/portal/finance','finance','对账开票'],['/portal/profile','settings','企业资料']]
const admin=[['/admin','home','采购驾驶舱'],['/admin/suppliers','supplier','供应商管理'],['/admin/sourcing','search','寻源与定价'],['/admin/orders','order','采购协同'],['/admin/delivery','truck','交付监控'],['/admin/quality','quality','质量管理'],['/admin/performance','chart','绩效评价'],['/admin/risk','risk','风险中心']]
const menus=props.mode==='portal'?portal:admin
function logout(){auth.logout();router.push('/login')}
</script>
<template><div class="app-shell" :class="`mode-${mode}`"><aside><div class="brand"><div class="brand-mark">ZH</div><div><b>知华 SRM</b><small>{{mode==='portal'?'供应商门户':'采购协同平台'}}</small></div></div><div class="company" v-if="mode==='portal'"><span>当前企业</span><b>上海华扬工业组件</b><small>供应商编码 SUP-2025-0048</small></div><nav><router-link v-for="m in menus" :key="m[0]" :to="m[0]"><AppIcon :name="m[1]"/><span>{{m[2]}}</span><em v-if="m[2]==='询报价'">3</em><em v-if="m[2]==='风险中心'" class="red">4</em></router-link></nav><div class="aside-foot"><span>社区源码版 · v1.0</span><a href="https://www.zhuatech.cn/" target="_blank">www.zhuatech.cn</a></div></aside><main><header><div><span class="workspace">{{mode==='portal'?'供应商工作区':'华东采购中心'}}</span><span class="period">业务日期 2026-07-29</span></div><div class="header-actions"><button class="icon-button"><AppIcon name="bell"/><i></i></button><div class="avatar">{{auth.user?.fullName?.slice(0,1)||'陈'}}</div><div class="user"><b>{{auth.user?.fullName|| (mode==='portal'?'顾洁':'陈屿')}}</b><small>{{mode==='portal'?'供应商业务经理':'采购经理'}}</small></div><button class="logout" @click="logout">退出</button></div></header><section class="page"><slot/></section></main></div></template>
