/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. */
package cn.zhuatech.srm.config;
import cn.zhuatech.srm.model.*; import cn.zhuatech.srm.repository.*; import org.springframework.boot.CommandLineRunner; import org.springframework.context.annotation.Bean; import org.springframework.context.annotation.Configuration; import org.springframework.security.crypto.password.PasswordEncoder; import java.math.BigDecimal; import java.time.*; import java.util.List;
@Configuration public class DataInitializer {
    @Bean CommandLineRunner seed(SupplierRepository suppliers,UserRepository users,SourcingEventRepository events,PurchaseOrderRepository orders,QualityIssueRepository quality,PasswordEncoder encoder){return args->{
        if(suppliers.count()>0)return;
        Supplier huayang=suppliers.save(new Supplier("SUP-2025-0048","上海华扬工业组件有限公司","工业连接器","顾洁","138****6208",Supplier.Status.ACTIVE,100,new BigDecimal("91.5"),new BigDecimal("96.80"),"LOW"));
        Supplier jingcheng=suppliers.save(new Supplier("SUP-2026-0126","苏州景澄精密制造有限公司","精密机加工","沈工","186****3812",Supplier.Status.ONBOARDING,72,new BigDecimal("84.0"),new BigDecimal("92.40"),"MEDIUM"));
        Supplier yunfan=suppliers.save(new Supplier("SUP-2024-0017","无锡云帆包装科技有限公司","包装材料","周琳","139****1056",Supplier.Status.ACTIVE,100,new BigDecimal("94.2"),new BigDecimal("98.10"),"LOW"));
        Supplier xinheng=suppliers.save(new Supplier("SUP-2025-0083","常州鑫恒电子科技有限公司","电子元器件","贺宁","177****8460",Supplier.Status.ACTIVE,100,new BigDecimal("78.6"),new BigDecimal("88.30"),"HIGH"));
        String demo=encoder.encode("Demo@2026");users.saveAll(List.of(new UserAccount("supplier",demo,"顾洁",UserAccount.Role.SUPPLIER,huayang),new UserAccount("buyer",demo,"陈屿",UserAccount.Role.BUYER,null),new UserAccount("auditor",demo,"林岚",UserAccount.Role.AUDITOR,null),new UserAccount("admin",encoder.encode("ZhuaTech@2026"),"系统管理员",UserAccount.Role.ADMIN,null)));
        events.saveAll(List.of(new SourcingEvent("RFQ-202607-021","年度工业连接器框架采购","工业连接器","陈屿",LocalDateTime.now().plusDays(1).plusHours(6),new BigDecimal("680000"),8,6,SourcingEvent.Status.OPEN),new SourcingEvent("RFQ-202607-018","三季度线束组件集中询价","线束组件","韩思远",LocalDateTime.now().plusDays(4),new BigDecimal("420000"),6,4,SourcingEvent.Status.OPEN),new SourcingEvent("RFP-202607-009","智能仓储周转箱联合开发","物流容器","陆琪",LocalDateTime.now().plusDays(8),new BigDecimal("760000"),5,3,SourcingEvent.Status.OPEN),new SourcingEvent("RFQ-202606-052","定制机柜附件采购","钣金件","陈屿",LocalDateTime.now().minusDays(5),new BigDecimal("315000"),7,7,SourcingEvent.Status.AWARDED)));
        orders.saveAll(List.of(new PurchaseOrder("PO-202607-0184",huayang,"M12 防水连接器 × 2,400",new BigDecimal("186420"),LocalDate.now().plusDays(14),35,PurchaseOrder.Status.PRODUCING),new PurchaseOrder("PO-202607-0198",huayang,"重载矩形连接器 × 860",new BigDecimal("126800"),LocalDate.now().plusDays(21),0,PurchaseOrder.Status.PENDING_ACK),new PurchaseOrder("PO-202606-0162",huayang,"工业航空插头 × 1,200",new BigDecimal("73200"),LocalDate.now().plusDays(6),80,PurchaseOrder.Status.PART_DELIVERED),new PurchaseOrder("PO-202607-0191",xinheng,"电源管理模块 × 600",new BigDecimal("248600"),LocalDate.now().plusDays(9),20,PurchaseOrder.Status.PRODUCING)));
        quality.saveAll(List.of(new QualityIssue("NCR-202607-014",huayang,"连接器锁紧扭矩抽检偏低","MAJOR",LocalDate.now().plusDays(4),"章皓",QualityIssue.Status.ANALYZING),new QualityIssue("CAR-202607-006",huayang,"包装标签批次字段缺失","MINOR",LocalDate.now().plusDays(9),"谢雯",QualityIssue.Status.VERIFYING),new QualityIssue("NCR-202607-017",xinheng,"模块耐压测试结果波动","CRITICAL",LocalDate.now().plusDays(2),"章皓",QualityIssue.Status.OPEN)));
    };}
}
